version: 2
formats: []

build:
  image: latest
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  